### ISSUE TITLE
[BUILD] 0.1.2 fails build on gcc 12.1.0, invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]

### ISSUE THREAD

**Issue by jamespharvey20** [olive-editor/olive#1970]
**Commit Hash**  https://github.com/olive-editor/olive/archive/0.1.2.tar.gz -- so, I think a449b04b, based on the git tag for 0.1.2.

**Platform**  Arch Linux

**Summary** Olive fails to compile, using gcc 12.1.0

**Additional Information / Output**

````
[ 37%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/paneffect.cpp.o
[ 37%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/richtexteffect.cpp.o
[ 38%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/shakeeffect.cpp.o
/build/olive/src/olive-0.1.2/dialogs/advancedvideodialog.cpp: In constructor ‘AdvancedVideoDialog::AdvancedVideoDialog(QWidget*, AVCodecID, VideoCodecParams&)’
:
/build/olive/src/olive-0.1.2/dialogs/advancedvideodialog.cpp:47:45: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
   47 |   AVCodec* codec_info = avcodec_find_encoder(static_cast<AVCodecID>(encoding_codec));
      |                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             const AVCodec*
[ 39%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/solideffect.cpp.o
[ 39%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/texteffect.cpp.o
[ 40%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/timecodeeffect.cpp.o
[ 41%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/toneeffect.cpp.o
[ 41%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/transformeffect.cpp.o
[ 42%] Building CXX object CMakeFiles/olive-editor.dir/effects/internal/voideffect.cpp.o
make[2]: *** [CMakeFiles/olive-editor.dir/build.make:264: CMakeFiles/olive-editor.dir/dialogs/advancedvideodialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/build/olive/src/olive-0.1.2/dialogs/exportdialog.cpp: In member function ‘void ExportDialog::add_codec_to_combobox(QComboBox*, AVCodecID)’:
/build/olive/src/olive-0.1.2/dialogs/exportdialog.cpp:124:45: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  124 |   AVCodec* codec_info = avcodec_find_encoder(codec);
      |                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~
      |                                             |
      |                                             const AVCodec*
/build/olive/src/olive-0.1.2/dialogs/exportdialog.cpp: In member function ‘void ExportDialog::vcodec_changed(int)’:
/build/olive/src/olive-0.1.2/dialogs/exportdialog.cpp:633:47: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  633 |     AVCodec* codec_info = avcodec_find_encoder(static_cast<AVCodecID>(vcodecCombobox->itemData(index).toInt()));
      |                           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               const AVCodec*
````

**Comment by itsmattkc** [comment]
Unfortunately, we don't support this version anymore. However if you wish to fix this, it should be as simple as changing that line `AVCodec* codec_info = avcodec_find_encoder(codec);` to `const AVCodec* codec_info = avcodec_find_encoder(codec);`
