### ISSUE TITLE
[BUILD] openimageio 3.x compatibility

### ISSUE THREAD

**Issue by 0-wiz-0** [olive-editor/olive#2392]
**Commit Hash** 7e0e94abf6610026aebb9ddce8564c39522fac6e

**Platform** NetBSD 

**Summary**
After the update of openimageio in pkgsrc to 3.0.9.1, the build of olive-editor started failing.

**Additional Information / Output**
The symptom is:
```
/scratch/multimedia/olive-editor/work/olive-7e0e94abf6610026aebb9ddce8564c39522fac6e/app/codec/oiio/oiiodecoder.cpp: In member function 'virtual olive::TexturePtr olive::OIIODecoder::RetrieveVideoInternal(const olive::Decoder::RetrieveVideoPa
rams&)':
/scratch/multimedia/olive-editor/work/olive-7e0e94abf6610026aebb9ddce8564c39522fac6e/app/codec/oiio/oiiodecoder.cpp:137:25: error: no matching function for call to 'OpenImageIO_v3_0::ImageInput::read_image(OpenImageIO_v3_0::TypeDesc::BASETYPE
&, char*, const OpenImageIO_v3_0::stride_t&, int)'
  137 |       image_->read_image(oiio_pix_fmt_, buffer_.data(), OIIO::AutoStride, buffer_.linesize_bytes());
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/scratch/multimedia/olive-editor/work/.buildlink/include/OpenImageIO/imageio.h:1435:18: note: candidate: 'virtual bool OpenImageIO_v3_0::ImageInput::read_image(int, int, int, int, OpenImageIO_v3_0::TypeDesc, void*, OpenImageIO_v3_0::stride_t,
 OpenImageIO_v3_0::stride_t, OpenImageIO_v3_0::stride_t, OpenImageIO_v3_0::ProgressCallback, void*)'
 1435 |     virtual bool read_image (int subimage, int miplevel,
      |                  ^~~~~~~~~~
/scratch/multimedia/olive-editor/work/.buildlink/include/OpenImageIO/imageio.h:1435:18: note:   candidate expects 11 arguments, 4 provided
/scratch/multimedia/olive-editor/work/olive-7e0e94abf6610026aebb9ddce8564c39522fac6e/app/codec/oiio/oiiodecoder.cpp:140:25: error: no matching function for call to 'OpenImageIO_v3_0::ImageInput::read_image(const OpenImageIO_v3_0::TypeDesc&, v
oid*, OpenImageIO_v3_0::stride_t, OpenImageIO_v3_0::stride_t, OpenImageIO_v3_0::stride_t)'
  140 |       image_->read_image(image_->spec().format, buf.localpixels(), buf.pixel_stride(), buf.scanline_stride(), buf.z_stride());
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/scratch/multimedia/olive-editor/work/.buildlink/include/OpenImageIO/imageio.h:1435:18: note: candidate: 'virtual bool OpenImageIO_v3_0::ImageInput::read_image(int, int, int, int, OpenImageIO_v3_0::TypeDesc, void*, OpenImageIO_v3_0::stride_t,
 OpenImageIO_v3_0::stride_t, OpenImageIO_v3_0::stride_t, OpenImageIO_v3_0::ProgressCallback, void*)'
 1435 |     virtual bool read_image (int subimage, int miplevel,
      |                  ^~~~~~~~~~
/scratch/multimedia/olive-editor/work/.buildlink/include/OpenImageIO/imageio.h:1435:18: note:   candidate expects 11 arguments, 5 provided
```

**Comment by Simran-B** [comment]
Olive doesn't have official BSD support, and I suppose the issue isn't present if you use the intended (outdated) versions of the dependencies that are known to work.

**Comment by gwuen** [comment]
Arch Linux is also affected by this, with openimageio 2.x not available in the repos anymore. I understand compatibility with version 3.x is not a priority, but cmake only checks for a minimum version:

https://github.com/olive-editor/olive/blob/7e0e94abf6610026aebb9ddce8564c39522fac6e/CMakeLists.txt#L93

I think there should be warning in place when trying to build against version 3.x. Right now, the build just fails and does not tell the user they have the wrong version.

PS: Olive successfully build against the latest 2.x release, version [2.5.18.0](https://github.com/AcademySoftwareFoundation/OpenImageIO/releases/tag/v2.5.18.0)

**Comment by rathann** [comment]
Same issue in Fedora, where we're rebasing OIIO to 3.x. I'm willing to attempt porting olive to OIIO 3.x. Help is welcome.
