### ISSUE TITLE
[RENDER] Correctly port shaders to ES

### ISSUE THREAD

**Issue by morrolinux** [olive-editor/olive#1737]
**Commit Hash** 
16aac5b

**Platform** 
Any

**Summary**
Just a reminder that current version of GLSL is 1.10 which is quite old (why?)
Also, updating to GLSL 3.0 **ES** would also enable ARM users to run Olive (which at the moment builds just fine but doesn't work on ARM because of GLSL 1.10) 

**Additional Information / Output**
This is obviously low priority but one thing to keep in mind I think.

**Comment by morrolinux** [comment]
5e66892 did not fix the original issue for me as it still uses GLSL 110

**Comment by itsmattkc** [comment]
My mistake, I switched it back for testing and forget to undo it.

**Comment by morrolinux** [comment]
Amazing. It does work indeed!

On a side note, here's some hopefully useful details:
1. In `openglrenderer.cpp`I had to force `kFormatUnsigned16` to `kFormatFloat16` like so:
```
  case VideoParams::kFormatUnsigned16:
/*
    switch (channel_layout) {
    case 1:
      return GL_R16;
    case 2:
      return GL_RG16;
    case 3:
      return GL_RGB16;
    case 4:
      return GL_RGBA16;
    }
    break; */
  case VideoParams::kFormatFloat16:
```

because of this error during make:

`openglrenderer.cpp:702:14: error: ‘GL_R16’ was not declared in this scope; did you mean ‘GL_R16F’?`

2. I can only make it work by switching the timeline to `8 bit` precision and disabling the auto-cache entirely. Any deviation from that will just render a black preview without errors in the shell.
